name: Application CI

on:
  pull_request:
    branches: [main]

jobs:
  next:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run format checker
        run: bun format:ci

      - name: Run linter
        run: bun lint:ci

      - name: Run type checker
        run: bun type:ci

      - name: Run integration tests
        run: bun test:ci

      - name: Build application
        run: bun run build

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install playwright browsers
        run: bunx playwright install --with-deps
      
      - name: Run playwright tests
        run: bun e2e:ci
      
      - name: Upload playwright test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
